### ISSUE TITLE
Committee Leader Election Process

### ISSUE THREAD

**Issue by uscffk** [xuchenhao001/AFL#4]
Does the committee-based consensus election aggregator need to implement it by itself? It seems that there is no implementation provided in the code.

**Comment by xuchenhao001** [comment]
Currently, the committee leader election process is ignored in the implementation. You are welcome to fork the project and implement your version.

**Comment by uscffk** [comment]
Thank you！Your code helped me a lot, I will try to complete the committee code.
I am trying to run your code but i have a problem：
I try to do federated learning with four devices：
epoch	acc-01	acc-02	acc-03	acc-04	acc-avg
0	10.54054	10.27027	9.729729	10.27027	10.20270225
1	82.16216	87.02702	85.13513	82.97297	84.32432
2	84.05405	88.91892	86.21621	83.24324	85.608105
3	83.78378	88.64865	85.94594	82.97297	85.337835
4	84.86486	86.75675	86.48648	86.21621	86.081075
5	86.21621	88.91892	87.02702	85.94594	87.0270225
6	85.67567	89.18918	86.48648	85.13513	86.621615
7	86.21621	89.18918	87.56756	85.13513	87.02702
8	87.02702	88.37837	88.1081	87.02702	87.6351275
9	86.21621	89.18918	87.83783	85.4054	87.162155
10	86.75675	87.56756	87.02702	85.13513	86.621615
11	86.48648	87.83783	87.56756	85.13513	86.75675
12	87.02702	88.64865	87.83783	86.48648	87.499995
13	87.02702	87.56756	87.02702	85.4054	86.75675
14	86.75675	87.83783	87.02702	85.94594	86.891885
15	86.48648	88.1081	87.56756	84.86486	86.75675
The correct rate of federated learning is increasing rapidly. Do I need to adjust the learning rate and the number of rounds of local training?

**Comment by xuchenhao001** [comment]
It is totally up to you. For different models/datasets, the performance of FL is usually largely different. Please feel free to adjust the parameters and find out the optimal solutions according to your research purposes.

I will close the issue. Please open new issues if you have any questions regarding this project.
