### ISSUE TITLE
About average test accuracy

### ISSUE THREAD

**Issue by uscffk** [xuchenhao001/AFL#5]
Hello, I still have one last question. How is your average test accuracy defined? The paper states that the correct rate of all nodes is averaged in a period of time. In your experiment, are you right in this Is the test accuracy of the same epoch averaged in the time period? In DBAFL, due to device heterogeneity, the test accuracy of different nodes in the same epoch should be quite different.

**Comment by xuchenhao001** [comment]
Yes, you are right. The test accuracy of different nodes in the same epoch is quite different. 

For example, at 100 seconds, Node 1 runs the 30th epoch, while Node 2 runs the 10th epoch. The average test accuracy is calculated by averaging the test accuracy of their latest epoch: average test accuracy = (test accuracy of Node 1 at 29th epoch) + (test accuracy of Node 2 at 9th epoch) / 2.

The calculation of the average test accuracy can be found [here](https://github.com/xuchenhao001/AFL/blob/main/federated-learning/results-merge/time-acc-extract.py#L37).

**Comment by uscffk** [comment]
Thank you so much for your help, it really helped me a lot
